name: SimpleRPG
version: ${project.version}
main: com.tyrriel.simplerpg.SimpleRPG
api-version: 1.13
authors: [Tyrriel]
depend: [ProtocolLib]
commands:
  class:
    description: Class selection
    usage: /class
  character:
    description: Admin Character Command
    usage: /character [addexp|setmoney|additem] <player> <number>